export const APPROUTES = {
  empty: '',
  noFound: '**',
  authentication: 'login',
  register: 'register',
  general: 'general',
  dashboard: 'dashboard',
  customers: 'customers',
  customerDetails: 'customer-details',
  administration: 'administration',
  vehicles: 'vehicles',
  rentACar: 'rent-a-car',
  reports: 'reports',
  users: 'users',
  coins: 'coins',
  companyDetails: 'company-details',
  documents: 'documents',
  employees: 'employees',
  employeeDetails: 'employees-details',
  accountSettings: 'account-settings',
  profile: 'profile',
  typeVehicles: 'type-vehicles',
  brandVehicles: 'brand-vehicles',
  vehicleModels: 'vehicle-models',
  invoice: 'invoice'
};
