export const APPROUTES = {
  empty: '',
  noFound: '**',
  general: 'general',
  authentication: 'login',
  dashboard: 'dashboard',
  register: 'register',
  accountSettings: 'account-settings',
  profile: 'profile',
  companies: 'companies',
  companyDetails: 'company-details',
  users: 'users',
  policies: 'policies',
  policyDetails: 'policy-details',
  customers: 'customers',
  customerDetails: 'customer-details',
  policy: 'policy',
  payments: 'payments',
  notifications: 'notifications',
  policyModification: 'policy-modification',
  policyModificationPrintPreview: 'policy-modification-print-preview',
};
